# Generated by Django 4.2.6 on 2023-10-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_campaign_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='project/images/'),
        ),
    ]
