# Generated by Django 4.2.6 on 2023-10-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_campaign_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='project/images/'),
        ),
    ]
