# Generated by Django 4.2.6 on 2023-10-23 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_campaign_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='images',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project/images/')),
                ('campaigns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagess', to='project.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='images',
            field=models.ManyToManyField(blank=True, to='project.image'),
        ),
    ]
