# Generated by Django 4.2.6 on 2023-10-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_campaign_images_image_campaign_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='project/images/'),
        ),
    ]
