# Generated by Django 4.2.6 on 2023-10-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='campaign',
            name='images',
            field=models.ImageField(blank=True, upload_to='project/images/'),
        ),
    ]
