# Generated by Django 4.2.6 on 2023-10-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_campaign_remove_donation_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='tags',
            field=models.ManyToManyField(blank=True, to='project.tag'),
        ),
    ]
