# Generated by Django 4.2.6 on 2023-10-24 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_image_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='campaign',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='project.campaign'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='campaign',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.campaign'),
        ),
    ]
