# Generated by Django 4.2.6 on 2023-10-24 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_comment_campaign_alter_image_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='campaign',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='project.campaign'),
        ),
    ]
